<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="CSCO-W-PF32ZV1R" failures="1" tests="3" name="com.java.qa.sccm.test.GetCustomerDataTest" time="3.421" errors="0" timestamp="2021-10-09T17:12:26 IST" skipped="0">
  <testcase classname="com.java.qa.sccm.test.GetCustomerDataTest" name="GetCustomer" time="0.881"/>
  <system-out>
    <![CDATA[Request URI : http://173.37.21.174/SCCM/sccm_api/web/api/v1/customers?customer_id=
Status code : 200
Response message : Response Messege : {
    "status_code": 5000,
    "sub_status_code": 5003,
    "error": "Customer Resource Not Found",
    "data": [
        
    ],
    "app_data": [
        
    ]
}]]>
  </system-out>
  <testcase classname="com.java.qa.sccm.test.GetCustomerDataTest" name="GetCustomer" time="1.693"/>
  <system-out>
    <![CDATA[Request URI : http://173.37.21.174/SCCM/sccm_api/web/api/v1/customers?customer_id=967572
Status code : 200
Response message : Response Messege : {
    "status_code": 1004,
    "sub_status_code": 1004,
    "message": "Customer Data Retrieval Successfully",
    "data": {
        "customer_id": "967572",
        "customer_name": "NEWAPI828",
        "services": [
            
        ]
    },
    "app_data": [
        
    ]
}]]>
  </system-out>
  <testcase classname="com.java.qa.sccm.test.GetCustomerDataTest" name="GetCustomer" time="0.847">
    <failure message="expected [5002] but found [5003]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [5002] but found [5003]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:617)
at com.java.qa.sccm.test.GetCustomerDataTest.GetCustomer(GetCustomerDataTest.java:84)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- GetCustomer -->
  <system-out>
    <![CDATA[Request URI : http://173.37.21.174/SCCM/sccm_api/web/api/v1/customers?customer_id=123213423453457000
Status code : 200
Response message : Response Messege : {
    "status_code": 5000,
    "sub_status_code": 5003,
    "error": "Customer Resource Not Found",
    "data": [
        
    ],
    "app_data": [
        
    ]
}]]>
  </system-out>
</testsuite> <!-- com.java.qa.sccm.test.GetCustomerDataTest -->
